create table if not exists public.dishes (
 id bigint generated by default as identity primary key,
 category text not null, price integer not null default 0 check (price between 0 and 10000000),
 image text not null, visible boolean not null default true, position integer not null default 0,
 names jsonb not null default '{}'::jsonb, descriptions jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.dishes enable row level security;
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('dish-images','dish-images',true,5242880,array['image/png','image/jpeg','image/webp'])
on conflict (id) do update set public=true,file_size_limit=5242880;
insert into public.dishes(category,price,image,visible,position,names,descriptions)
select 'Osh',13000,'/assets/osh.png',true,1,'{"uz":"Osh","ko":"오시","ru":"Плов","en":"Plov"}'::jsonb,'{"uz":"An’anaviy o‘zbek palovi","ko":"전통 우즈베크 플로브","ru":"Традиционный узбекский плов","en":"Traditional Uzbek plov"}'::jsonb
where not exists(select 1 from public.dishes);
