import { Inter } from "next/font/google";
import "./globals.css";
import "./auth.css";
import "./admin-desktop.css";
import "./menu-fixes.css";
import "./menu-hero.css";
import "./language-menu.css";
import "./language-menu-fix.css";
import "./category-compact.css";
import "./header-align.css";
import "./admin-category-clean.css";
import "./floating-cart.css";
import "./mobile-premium.css";
import "./mobile-design-v2.css";
import "./kitchen-vibe.css";
import "./restaurant-polish.css";
import "./signature-restaurant.css";
import "./admin-pro-v2.css";
import "./admin-clean-essential.css";
import "./loader-hero-tune.css";
import "./banner-height-tune.css";
import "./hero-logo-only.css";
import "./loader-logo-only.css";
import "./classic-menu-refine.css";
import "./mobile-premium-v4.css";
import "./mobile-logo-category.css";
const inter=Inter({subsets:["latin"],variable:"--font-inter"});
export const metadata={title:"CHAYKAHANA",description:"O‘zbek taomlari menyusi"};
export default function RootLayout({children}){return <html lang="uz"><body className={inter.variable}>{children}</body></html>}
