"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { ArrowLeft, BowlFood, CheckCircle, DotsSixVertical, Eye, EyeSlash, FloppyDisk, ImageSquare, MagnifyingGlass, Plus, SpinnerGap, Trash } from "@phosphor-icons/react";

const langs = { uz: "UZ", ko: "한국어", ru: "RU", en: "EN" };
const emptyNames = { uz: "", ko: "", ru: "", en: "" };
const newDish = (category) => ({ category: category || "Osh", price: 0, image: "/assets/osh.png", visible: true, position: 0, names: { ...emptyNames, uz: "Yangi taom" }, descriptions: { ...emptyNames } });
const newCategory = () => ({ visible: true, position: 0, names: { ...emptyNames, uz: "Yangi kategoriya" } });

export default function AdminClient() {
  const router = useRouter();
  const [items, setItems] = useState([]), [categories, setCategories] = useState([]), [view, setView] = useState("dashboard");
  const [selectedId, setSelectedId] = useState(null), [draft, setDraft] = useState(null), [selectedCategoryId, setSelectedCategoryId] = useState(null), [categoryDraft, setCategoryDraft] = useState(null);
  const [query, setQuery] = useState(""), [categoryFilter, setCategoryFilter] = useState("all"), [lang, setLang] = useState("uz"), [notice, setNotice] = useState("");
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [categoryError, setCategoryError] = useState(""), [mobileEdit, setMobileEdit] = useState(false);

  const api = async (url, options) => { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Server xatosi"); return data; };
  const load = useCallback(async () => {
    const dishes = await api("/api/dishes?admin=1", { cache: "no-store" }); setItems(dishes); setError("");
    let cats = [];
    try { cats = await api("/api/categories?admin=1", { cache: "no-store" }); setCategories(cats); setCategoryError(""); }
    catch (categoryLoadError) { setCategories([]); setCategoryError(categoryLoadError.message); }
    return { dishes, cats };
  }, []);

  useEffect(() => { load().then(({ dishes, cats }) => { if (dishes[0]) { setSelectedId(dishes[0].id); setDraft(structuredClone(dishes[0])); } if (cats[0]) { setSelectedCategoryId(cats[0].id); setCategoryDraft(structuredClone(cats[0])); } }).catch((loadError) => setError(loadError.message)).finally(() => setLoading(false)); }, [load]);

  const categoryName = useCallback((id, language = "uz") => { const category = categories.find((item) => item.id === id); return category?.names?.[language] || category?.names?.uz || id; }, [categories]);
  const fallbackCategories = useMemo(() => [...new Set(items.map((item) => item.category))].map((id, index) => ({ id, names: { ...emptyNames, uz: id }, visible: true, position: 1000 + index })), [items]);
  const dishCategories = categories.length ? categories : fallbackCategories;
  const grouped = useMemo(() => items.filter((item) => item.names.uz.toLowerCase().includes(query.toLowerCase()) && (categoryFilter === "all" || item.category === categoryFilter)).reduce((result, item) => { (result[item.category] ??= []).push(item); return result; }, {}), [items, query, categoryFilter]);
  const categoryCounts = useMemo(() => items.reduce((result, item) => { result[item.category] = (result[item.category] || 0) + 1; return result; }, {}), [items]);

  const toast = (message) => { setNotice(message); setTimeout(() => setNotice(""), 1800); };
  const act = async (fn, success) => { if (busy) return; setBusy(true); try { await fn(); toast(success); } catch (actionError) { toast(actionError.message); } finally { setBusy(false); } };
  const switchView = (nextView) => { setView(nextView); setMobileEdit(false); setNotice(""); };

  const saveDish = () => act(async () => { await api(`/api/dishes/${draft.id}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(draft) }); await load(); }, "Taom saqlandi");
  const addDish = () => act(async () => { const created = await api("/api/dishes", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(newDish(dishCategories[0]?.id || "Osh")) }); await load(); setSelectedId(created.id); setDraft(created); setMobileEdit(true); }, "Yangi taom qo‘shildi");
  const removeDish = async () => { if (!confirm("Taom o‘chirilsinmi?")) return; act(async () => { await api(`/api/dishes/${draft.id}`, { method: "DELETE" }); const { dishes } = await load(); setSelectedId(dishes[0]?.id ?? null); setDraft(dishes[0] ? structuredClone(dishes[0]) : null); setMobileEdit(false); }, "Taom o‘chirildi"); };

  const saveCategory = () => act(async () => { const updated = await api(`/api/categories/${encodeURIComponent(categoryDraft.id)}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(categoryDraft) }); await load(); setSelectedCategoryId(updated.id); setCategoryDraft(updated); }, "Kategoriya saqlandi");
  const addCategory = () => act(async () => { const created = await api("/api/categories", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(newCategory()) }); await load(); setSelectedCategoryId(created.id); setCategoryDraft(created); setMobileEdit(true); }, "Yangi kategoriya qo‘shildi");
  const removeCategory = async () => { if (!confirm("Kategoriya o‘chirilsinmi?")) return; act(async () => { await api(`/api/categories/${encodeURIComponent(categoryDraft.id)}`, { method: "DELETE" }); const { cats } = await load(); setSelectedCategoryId(cats[0]?.id ?? null); setCategoryDraft(cats[0] ? structuredClone(cats[0]) : null); setMobileEdit(false); }, "Kategoriya o‘chirildi"); };
  const logout = async () => { await fetch("/api/auth/logout", { method: "POST" }); router.push("/admin/login"); };
  const image = async (event) => { const file = event.target.files?.[0]; if (!file) return; const form = new FormData(); form.set("file", file); await act(async () => { const data = await api("/api/uploads", { method: "POST", body: form }); setDraft((current) => ({ ...current, image: data.url })); }, "Rasm yuklandi"); };

  if (loading) return <div className="admin-loading"><SpinnerGap/>Admin panel yuklanmoqda…</div>;
  if (error) return <div className="admin-loading"><b>{error}</b><button onClick={() => location.reload()}>Qayta urinish</button></div>;

  const selector = <select value={view} onChange={(event) => switchView(event.target.value)} aria-label="Admin bo‘limi" style={{ height: 42, border: "1px solid #ccd6e4", borderRadius: 9, background: "#fff", padding: "0 10px", color: "#173159" }}><option value="dashboard">Dashboard</option><option value="dishes">Taomlar</option><option value="categories">Kategoriyalar</option></select>;
  const sidebar = <aside className="admin-side"><div className="admin-brand"><span>✦</span><b>CHAYKAHANA</b></div><nav><button className={view === "dashboard" ? "active" : ""} onClick={() => switchView("dashboard")}><CheckCircle/>Dashboard</button><button className={view === "dishes" ? "active" : ""} onClick={() => switchView("dishes")}><BowlFood/>Taomlar</button><button className={view === "categories" ? "active" : ""} onClick={() => switchView("categories")}><DotsSixVertical/>Kategoriyalar</button></nav><Link href="/">← Menyuni ko‘rish</Link><button className="logout" onClick={logout}>Chiqish</button></aside>;

  if (view === "dashboard") {
    const visible = items.filter((item) => item.visible).length, hidden = items.length - visible, visibleCategories = categories.filter((item) => item.visible).length;
    return <main className="admin-shell" style={{ gridTemplateColumns: "220px 1fr" }}>{sidebar}<section className="admin-list" style={{ borderRight: 0 }}><header><div><h1>Dashboard</h1><small>Menu holati va tezkor ko‘rsatkichlar</small></div>{selector}</header><div style={{ overflow: "auto", padding: 24 }}>
      {categoryError && <div style={{ marginBottom: 18, padding: 14, borderRadius: 12, background: "#fff4df", border: "1px solid #f1d39b" }}><b>Kategoriya bazasi ulanmagan.</b><div style={{ marginTop: 5, color: "#775b28" }}>Supabase’da yangilangan <code>supabase/migration.sql</code> faylini ishga tushiring.</div></div>}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(190px,1fr))", gap: 16, marginBottom: 24 }}>{[["Jami taomlar", items.length], ["Ko‘rinadigan", visible], ["Yashirin", hidden], ["Kategoriyalar", categories.length], ["Aktiv kategoriyalar", visibleCategories]].map(([label, value]) => <div key={label} style={{ background: "#fff", border: "1px solid #d9e2ef", borderRadius: 16, padding: 20, boxShadow: "0 8px 24px rgba(14,49,98,.06)" }}><small style={{ color: "#73819a" }}>{label}</small><div style={{ fontSize: 32, fontWeight: 800, marginTop: 8 }}>{value}</div></div>)}</div>
      <div style={{ background: "#fff", border: "1px solid #d9e2ef", borderRadius: 16, padding: 20 }}><h2 style={{ marginTop: 0 }}>Kategoriyalar bo‘yicha taomlar</h2>{(categories.length ? categories : fallbackCategories).map((category) => <div key={category.id} style={{ display: "flex", justifyContent: "space-between", gap: 16, padding: "12px 0", borderBottom: "1px solid #edf1f6" }}><span>{category.names.uz || category.id}</span><b>{categoryCounts[category.id] || 0} ta</b></div>)}</div>
    </div></section></main>;
  }

  if (view === "categories") return <main className={`admin-shell ${mobileEdit ? "mobile-edit" : ""}`}>{sidebar}<section className="admin-list"><header><div><h1>Kategoriyalar</h1><small>{categories.length} ta kategoriya</small></div><div style={{ display: "flex", gap: 8, alignItems: "center" }}>{selector}<button disabled={busy || Boolean(categoryError)} onClick={addCategory}><Plus/>Yangi</button></div></header>
    {categoryError ? <div className="admin-empty" style={{ padding: 24, textAlign: "center" }}><b>Kategoriyalar bazasi tayyor emas</b><p>{categoryError}</p><small>Supabase’da yangilangan migration.sql faylini ishga tushiring.</small></div> : <div className="admin-items"><div><h3>Kategoriyalar <em>{categories.length}</em></h3>{categories.map((category) => <button className={category.id === selectedCategoryId ? "selected" : ""} key={category.id} onClick={() => { setSelectedCategoryId(category.id); setCategoryDraft(structuredClone(category)); setMobileEdit(true); }}><span className="admin-thumb" style={{ display: "grid", placeItems: "center", background: "#edf4ff", color: "#0c63f4", fontWeight: 800, fontSize: 18 }}>#</span><span><b>{category.names.uz || category.id}</b><small>{categoryCounts[category.id] || 0} ta taom</small></span><i className={category.visible ? "on" : ""}>{category.visible ? <Eye/> : <EyeSlash/>}</i><DotsSixVertical/></button>)}</div></div>}
    </section><section className="admin-editor">{categoryDraft ? <><header><button className="admin-back" onClick={() => setMobileEdit(false)}><ArrowLeft/></button><div><h2>{categoryDraft.names.uz}</h2><small>Kategoriya ma’lumotlarini tahrirlash</small></div><div><button disabled={busy} className="save" onClick={saveCategory}>{busy ? <SpinnerGap/> : <FloppyDisk/>}Saqlash</button><button disabled={busy} className="delete" onClick={removeCategory}><Trash/>O‘chirish</button></div></header>{notice && <div className="notice"><CheckCircle/>{notice}</div>}<div className="editor-body"><h3>Asosiy ma’lumotlar</h3><div className="admin-fields" style={{ maxWidth: 520 }}><label>Ichki ID<input value={categoryDraft.id} disabled/></label><label>Tartib<input min="0" max="100000" type="number" value={categoryDraft.position} onChange={(event) => setCategoryDraft((current) => ({ ...current, position: Number(event.target.value) }))}/></label><label>Ko‘rinish<button type="button" onClick={() => setCategoryDraft((current) => ({ ...current, visible: !current.visible }))}>{categoryDraft.visible ? <Eye/> : <EyeSlash/>}{categoryDraft.visible ? "Ko‘rinadi" : "Yashirin"}</button></label></div><div className="admin-tabs">{Object.entries(langs).map(([key, label]) => <button key={key} className={lang === key ? "active" : ""} onClick={() => setLang(key)}>{label}</button>)}</div><div className="locale-grid" style={{ gridTemplateColumns: "1fr" }}><label>Kategoriya nomi ({langs[lang]})<input value={categoryDraft.names[lang] || ""} onChange={(event) => setCategoryDraft((current) => ({ ...current, names: { ...current.names, [lang]: event.target.value } }))}/></label></div></div></> : <div className="admin-empty"><DotsSixVertical/><h2>Hali kategoriya yo‘q</h2><button onClick={addCategory}><Plus/>Birinchi kategoriyani qo‘shish</button></div>}</section></main>;

  return <main className={`admin-shell ${mobileEdit ? "mobile-edit" : ""}`}>{sidebar}<section className="admin-list"><header><div><h1>Taomlar</h1><small>{items.length} ta taom</small></div><div style={{ display: "flex", gap: 8, alignItems: "center" }}>{selector}<button disabled={busy || !dishCategories.length} onClick={addDish}><Plus/>Yangi taom</button></div></header>
    <div style={{ display: "flex", gap: 8, margin: "17px" }}><label className="admin-search" style={{ margin: 0, flex: 1 }}><MagnifyingGlass/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Taom qidirish"/></label><select value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)} style={{ minWidth: 125, border: "1px solid #cfd9e7", borderRadius: 9, background: "#fff", padding: "0 10px" }}><option value="all">Barchasi</option>{dishCategories.map((category) => <option key={category.id} value={category.id}>{category.names.uz || category.id}</option>)}</select></div>
    <div className="admin-items">{Object.entries(grouped).map(([categoryId, foods]) => <div key={categoryId}><h3>{categoryName(categoryId)} <em>{foods.length}</em></h3>{foods.map((dish) => <button className={dish.id === selectedId ? "selected" : ""} key={dish.id} onClick={() => { setSelectedId(dish.id); setDraft(structuredClone(dish)); setMobileEdit(true); }}><span className="admin-thumb"><Image src={dish.image} fill sizes="58px" alt=""/></span><span><b>{dish.names.uz}</b><small>₩{dish.price.toLocaleString()}</small></span><i className={dish.visible ? "on" : ""}>{dish.visible ? <Eye/> : <EyeSlash/>}</i><DotsSixVertical/></button>)}</div>)}</div>
  </section><section className="admin-editor">{draft ? <><header><button className="admin-back" onClick={() => setMobileEdit(false)}><ArrowLeft/></button><div><h2>{draft.names.uz}</h2><small>Taom ma’lumotlarini tahrirlash</small></div><div><button disabled={busy} className="save" onClick={saveDish}>{busy ? <SpinnerGap/> : <FloppyDisk/>}Saqlash</button><button disabled={busy} className="delete" onClick={removeDish}><Trash/>O‘chirish</button></div></header>{notice && <div className="notice"><CheckCircle/>{notice}</div>}<div className="editor-body"><h3>Asosiy ma’lumotlar</h3><div className="editor-basic"><div><label>Rasm</label><div className="admin-preview"><Image src={draft.image} fill sizes="(max-width: 640px) 100vw, 50vw" alt={draft.names.uz}/><label><ImageSquare/>Rasmni o‘zgartirish<input disabled={busy} type="file" accept="image/png,image/jpeg,image/webp" onChange={image}/></label></div></div><div className="admin-fields"><label>Kategoriya<select value={draft.category} onChange={(event) => setDraft((current) => ({ ...current, category: event.target.value }))}>{!dishCategories.some((category) => category.id === draft.category) && <option value={draft.category}>{draft.category}</option>}{dishCategories.map((category) => <option key={category.id} value={category.id}>{category.names.uz || category.id}</option>)}</select></label><label>Narx (₩)<input min="0" max="10000000" type="number" value={draft.price} onChange={(event) => setDraft((current) => ({ ...current, price: Number(event.target.value) }))}/></label><label>Ko‘rinish<button type="button" onClick={() => setDraft((current) => ({ ...current, visible: !current.visible }))}>{draft.visible ? <Eye/> : <EyeSlash/>}{draft.visible ? "Ko‘rinadi" : "Yashirin"}</button></label></div></div><div className="admin-tabs">{Object.entries(langs).map(([key, label]) => <button key={key} className={lang === key ? "active" : ""} onClick={() => setLang(key)}>{label}</button>)}</div><div className="locale-grid"><label>Nomi ({langs[lang]})<input value={draft.names[lang] || ""} onChange={(event) => setDraft((current) => ({ ...current, names: { ...current.names, [lang]: event.target.value } }))}/></label><label>Tavsif ({langs[lang]})<textarea value={draft.descriptions[lang] || ""} onChange={(event) => setDraft((current) => ({ ...current, descriptions: { ...current.descriptions, [lang]: event.target.value } }))}/></label></div></div></> : <div className="admin-empty"><BowlFood/><h2>Hali taom yo‘q</h2><button onClick={addDish}><Plus/>Birinchi taomni qo‘shish</button></div>}</section></main>;
}
